---
title: 'Data Analysis as an R Package: The How'
author: 'Sara Biddle'
date: '2023-12-08'
slug: dat-anls-as-pkg-how
categories: ["R"]
tags: ["devtools", "usethis"]
---

### Before You Begin

#### Project Goals

This post is geared specifically towards creating a package that demonstrates your data analysis process and communicates the results of this data analysis. The package will include data that goes along with the analysis. The package is not intended to create robust data analysis tools for others to use.

If you are interested in creating a package that helps others conduct similar analyses to yours, this may not be the post for you.

#### Preparation

You will need R, RStudio, Git, GitHub, and Markdown.

If you have not set up your R ecosystem to integrate Git, R, and Markdown, read my post [Setting Up Your R Ecosystem][post-r-eco]. This will help you set up your tools to be ready for everything described in this post.

##### Projects and Directories

There are three types of projects or directories that you will be working in. 

**R Project**
: open files and environment contents in R Studio

**Active `usethis` Project**
: directory that `usethis` and `devtools` act upon when called

**Working Directory**
: directory you are currently working in

These should, generally, all be the same. 

The R Project is what you see in R Studio when you open it up. The R Project will remember what you are working on. That way, if you want to work on other things, you can close the project and re-open it later and pick up right where you left off.  You can switch between projects using the dropdown in the upper right hand corner of R Studio. When you switch projects, R Studio opens the files and loads the environment as it was when you last left that project and starts a new R Session. 

The working directory is what shows up in the `Files` pane of R Studio. You can navigate around the directory, but the top level working directory is `Home > projectname` in that pane. 

### Starting a Project

Start a clean R project. If you've already started work on the data analysis, that's okay. You can bring files over to the new project if needed. I recommend using a new, clean project to ensure that Git and the package development tools get off to a good start. It can be messy to convert an existing, non-package project to a package on GitHub. 

I have found the easiest way to be:

#### 1. Create a New GitHub Repository

When naming the repo, remember that you will be making an R package. So you need to follow both Git and R's naming conventions. Git allows you to name repos with special characters such as '-', but R will not allow you to name your package that way. You could, technically, name the R package and Git repo differently, but I definitely prefer matching names just to prevent any unnecessary confusion. 

Choose a name that is all characters, no '-' or other special characters, and preferably no numeric characters. For further information about package naming conventions, read [R Packages 2e Chapter 4.1.2: Name Your Package][rpackages4.1.2url]. Note that the purpose of your package is different than the kind of packages that the author is discussing in [R Packages 2e][rpackagesurl]. The package we are creating is for data analysis of a specific study or project, not to develop tools in R for others to use. You will not likely submit this package to CRAN or BioConductor, as this package will have limited usefulness for others besides you and the team working on this data analysis. So you can be a little more relaxed with the naming rules than would be required for you to submit to CRAN or BioConductor. 

Under the option for selecting a `.gitignore` template, select the option for `R`.

You can go ahead and choose a license or you can choose one later, it is up to you. If you are not sure which license to choose, you can click on the link by the license selection options to read over some popular options and what they do. I default to an MIT license, but if your study has data that should not be publicly available or used by others, then spend time choosing a good license with the protections you want. 
    
#### 2. Create a New R Project

In RStudio, click 'File' in the upper left corner and then 'New Project...'  This will open a pop up with three options: 'New Directory', 'Existing Directory', and 'Version Control'. Select 'Version Control'. In the next pop up, choose Git, and in the next pop up put in the URL to the newly created GitHub repo. This will automatically name the new project directory the same as the repo. Choose where you want to directory to live on your computer and make sure the check box in the bottom left for 'Open in new session' is selected. Click 'Create Project'. These steps are covered in more depth in [Happy Git and GitHub for the UseR Chapter 15: New Project, GitHub First][HappyGitWithRChapter15URL], and if you have any errors during this process that is where I would look for help.
    
#### 3. Create the Package

Run the following command in the console:

```
devtools::create_package("path/to/project")
```
    
When you run this command, you will get a lot of output in the console. It should look like this:

```
devtools::create_package("path/to/project")
#> Setting active project to 'path/to/project/projectname'
#> Creating 'R/'
#> Writing 'DESCRIPTION'
#> ...
#> Writing 'NAMESPACE'
#> Overwrite pre-existing file 'projectname.Rproj'?
#> 1: For sure
#> 2: Negative
#> 3: Nope
```

I like to let it overwrite the existing R Project. You shouldn't have anything important in the existing one since all we have done so far is project set up. This lets `devtools` set up everything the way it likes and prevents any weird issues later on. 

Make your choice by typing the corresponding number into the console and pressing `enter`. 

If you choose to overwrite, a new R Studio session will open up. Close the old R Studio Session. 

Check that your current RStudio project, active `usethis` project, and working directory are the same by running the command `usethis::proj_sitrep()` in the console and checking the output.

```
usethis::proj_sitrep()
#> *      working_directory: 'Users/SaraBiddle/path/to/project'
#> * active_usethis_project: 'Users/SaraBiddle/path/to/project'
#> * active_rstudio_project: 'Users/SaraBiddle/path/to/project' 
```

If your projects and directories do not match, try running `usethis::proj_activate('path/to/project')` and re-checking with `usethis::proj_sitrep()`. 

**Do not mess with your working directory.** Leave it as the top-level of your package. This is per the recommendation of [R Packages 2e Chapter 4.3: Working directory and file path discipline][rpackagesch4.3url] and the reasoning behind it can be found there. 

Take a look in the file window of RStudio. You will see several new files and folders there that were created when you ran `create_package()`. Perfect!

#### 4. Initial Commit and Push

Open up the `DESCRIPTION` file at the top level of your package. It should look similar to this:

```
Package: mypackagename
Title: What the Package Does (One Line, Title Case)
Version: 0.0.0.9000
Authors@R:
    person("First", "Last", , "first.last@example.com", role = c("aut","cre"),
    comment = c(ORCID = "YOUR-ORCID-ID"))
Description: What the package does (one paragraph).
License: `use_mit_license()`, `use_gpl3_license()` or friends to pick a
    license
Encoding: UTF-8
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.2.3
```

Edit the 'Title' field and give your package a title. I like to use something like 'Data Analysis for xyz Project' which keeps it short and sweet. Edit the 'Description' field. This is where you can include a few more details about the project and what is included in the package. This is still relatively short, only one paragraph in length. 

When formatting the 'Description' field, subsequent lines are indented four spaces. 

\\TODO editing the authors field

Close the 'DESCRIPTION' file.

If you did not choose a license option when creating the GitHub repository, choose one now.  Use the appropriate `usethis` function in the console. 

If you were to choose the MIT license, you would run the following command in the console:

```
usethis::use_mit_license()
```

If you still have the 'DESCRIPTION' file open, this command will not be able to edit the license field in the file. 

As you develop your package, if you use `devtools` and `usethis` appropriately, all of the other fields in the 'DESCRIPTION' will be updated and maintained properly.

For a more detailed look at the purpose and use of the 'DESCRIPTION' file, read [R Packages (2e) Chapter 9.1: The DESCRIPTION FILE][rpackagesch9.1url].

I like to commit and push after editing the description and choosing a license. This confirms that Git is still connected with my project and gets all the set up files staged and out of the way. 

### Working in the Project

#### Raw Data

Run the function `usethis::use_raw_data()` in the console.

This function sets up the `data-raw` directory in your package. 

Move all your raw data files into the `data-raw` directory. You can create subdirectories within the `data-raw` directory if you need to organize them further. 

Commit and push `data-raw` and its contents. 

You can always add other files to `data-raw` later if you forgot some or are doing your analysis in parts and don't want the files you don't yet need in your directory, for whatever reason.

Create a new R script file. This file will have the code used to clean your raw data files and get it into a format that is consistent and easily usable for later parts of your analysis. You should not be doing any of the analysis in this file, it is just the data cleaning!

It should look something like this:

```
rawdata <- read_in('raw_data_file_name.ext') |>
    dplyr::rename("NewName" = oldname) |>
    dplyr::otherCleaningFunctions
```

Include comments as necessary for explanation.

At the end of the script, there should be the following function:

```
usethis::use_data(nameofrawdata)
```

This saves the cleaned data frame in the file `nameofrawdata.rda` in the directory `data`. 

Save this script in the `data-raw` directory. I like to name the script to match the data saved under `data`. 

Repeat as necessary for all the data you want to have cleaned. 

For every object you save in `data/`, you will need to document it. 

Under `R/`, create `data.R`. This file will contain the `roxygen2` documentation of everything stored under `data/`. 

The R script files that contain the code you write can follow a few different different naming conventions. Just be consistent!

You can put each individual function in its own `.R` file that is named `nameofthefunction.R`. Each file will be named by the individual function contained within it.

You can group several related functions together. For example, if you write an S3 method, you can put the method and its helpers in the same file and name it `nameoftheS3method.r`. Or, if you have several functions that do similar things, such as several custom written plotting or graphing functions, you can put them in the same file and name it something like `plot.R`. 

Each `.R` file under the `R` subdirectory should have a parallel file under the `testthat` subdirectory that contains tests for the code you wrote. 



The `roxygen2` package helps greatly reduce the burden of documentation and keeps your documentation clear and consistent. 

`roxygen2` helps you create these pages without extra work on your end. You don't have to write the Markdown by hand, you just have to put the appropriate `roxygen2` tags by your function.

`roxygen2` can also document your data sets! A documentation block for a dataset looks something like the following:

```
#' Title of my Dataset
#'
#' Longer description of my dataset, including details such as how
#' it was collected and what types of data it includes...
#'
#' @format ##`nameofdataset`
#' A data frame with n rows and m columns.
#' \describe{
#'     \item{columnname}{Column Description}
#'     \item{columnname}{Column Description}
#'     ...
#' }
#' @source <url or other source information>
"nameofdataset"
```


[HappyGitWithRChapter15URL]:https://happygitwithr.com/new-github-first
[rpackages4.1.2url]:https://r-pkgs.org/workflow101.html#name-your-package
[rpackagesch4.3url]:https://r-pkgs.org/workflow101.html#working-directory-and-filepath-discipline
[rpackagesurl]:https://r-pkgs.org/
[post-r-eco]: https://saragracebiddle-blog.netlify.app/2023-12-08-r-eco
[rpackagesch9.1url]:https://r-pkgs.org/description.html#the-description-file
